export enum PlanogramDragDropTypes {
    SECTION_SIDEBAR = "SECTION_SIDEBAR",
    SECTION = "SECTION",
    SHELF_SIDEBAR = "SHELF_SIDEBAR",
    SHELF_PRODUCT = "SHELF_PRODUCT",
    SHELF = "SHELF",
    SHELF_ITEM = "SHELF_ITEM",
    PRODUCT_SIDEBAR = "PRODUCT_SIDEBAR",
    PRODUCT = "PRODUCT_GARBAGE",
    AISLE = "AISLE",
    TRASH = "TRASH"
}